const express = require("express")
const userAuth = require("../controller/userAuth")
const Routes = express.Router()
Routes.post("/auth/register",userAuth.register)
Routes.post("/auth/login",userAuth.loginUser)
Routes.post("/auth/verifyOtp",userAuth.loginWithPhone)
Routes.post("/auth/password-reset",userAuth.resetUserPassword)
Routes.post("/auth/save-password/:id/:authorization",userAuth.saveResetPassword)
Routes.post("/addUserOffice",userAuth.addUserOffice)
Routes.post("/addUserBank",userAuth.addUserBank)
Routes.post("/addUserLeave",userAuth.addUserLeave)
Routes.post("/addUserSalary",userAuth.addUserSalary)
Routes.post("/addUserLoan",userAuth.addUserLoan)
Routes.post("/punchIn",userAuth.punchIn)
Routes.put("/punchOut",userAuth.punchOut)
module.exports = Routes