const express = require("express")
const Routes = express.Router()
const mastercontroller = require("../controller/masterController")
Routes.get("/getCountry",mastercontroller.getCountry)
Routes.post("/addCountry",mastercontroller.addCountry)
Routes.get("/getState",mastercontroller.getState)
Routes.post("/addState",mastercontroller.addState)
Routes.get("/getCity",mastercontroller.getCity)
Routes.post("/addCity",mastercontroller.addCity)
Routes.get("/getDesignation/:id",mastercontroller.getDesignation)
Routes.get("/getDesignation",mastercontroller.getDesignation)
Routes.post("/addDesignation",mastercontroller.addDesignation)
Routes.get("/getDepartment",mastercontroller.getDepartment)
Routes.post("/addDepartment",mastercontroller.addDepartment)
Routes.delete("/deleteDesignation/:id",mastercontroller.deleteDesignation)
Routes.delete("/deleteDepartment/:id",mastercontroller.deleteDepartment)
Routes.get("/getCity/:id",mastercontroller.getCity)
Routes.get("/getState/:id",mastercontroller.getState)
Routes.get("/getDepartmentList",mastercontroller.getDepartmentList)
Routes.get("/getTimezone/:id",mastercontroller.getTimezone)
Routes.post("/addProperty",mastercontroller.addProperty)
Routes.post("/addProject",mastercontroller.addProject)
Routes.post("/addDeveloper",mastercontroller.addDeveloper)
Routes.get("/getDeveloper",mastercontroller.getDeveloper)
Routes.get("/getProject",mastercontroller.getProject)
Routes.get("/getProject/:id",mastercontroller.getProject)
Routes.get("/getDeveloperTree",mastercontroller.getDeveloperTree)
Routes.get("/getDeveloperTree/:id",mastercontroller.getDeveloperTree)
Routes.delete("/deleteProject/:id",mastercontroller.deleteProject)
module.exports = Routes