const express = require("express")
const Routes = express.Router()
const mastercontroller = require("../controller/masterController")
Routes.get("/getCountry",mastercontroller.getCountry)
Routes.post("/addCountry",mastercontroller.addCountry)
Routes.get("/getState",mastercontroller.getState)
Routes.post("/addState",mastercontroller.addState)
Routes.get("/getCity",mastercontroller.getCity)
Routes.post("/addCity",mastercontroller.addCity)
Routes.get("/getDesignation/:id",mastercontroller.getDesignation)
Routes.get("/getDesignation",mastercontroller.getDesignation)
Routes.post("/addDesignation",mastercontroller.addDesignation)
Routes.get("/getDepartment",mastercontroller.getDepartment)
Routes.post("/addDepartment",mastercontroller.addDepartment)
Routes.delete("/deleteDesignation/:id",mastercontroller.deleteDesignation)
Routes.delete("/deleteDepartment/:id",mastercontroller.deleteDepartment)
module.exports = Routes